### ISSUE TITLE
Support for small screens

### ISSUE THREAD

**Issue by quanta-kt** [ANSHIKA1806/PhotoEditor#12]
Currently, the site doesn't implement any responsiveness and is pretty non-functional on mobile
Screenshot:
![image](https://user-images.githubusercontent.com/40241646/136665019-46cc393c-ddb9-4634-b53c-fbf8541f3c42.png)

I do have a layout in mind, everything stacking vertically, the image being the top most followed by the editor tools below it, and the instructions can sit below them at the bottom.

I am willing to work on this

**Comment by PranavTrip** [comment]
Hey please assign this to me I can work on the above mentioned idea.

**Comment by ANSHIKA1806** [comment]
Now It is responsive.
So no need 
You can contribute in other ways.
