### ISSUE TITLE
Responsiveness in mobile view

### ISSUE THREAD

**Issue by vaishnav-sh** [ANSHIKA1806/PhotoEditor#19]
I would like to work on this issue. 
![Screenshot_2021-10-10-11-40-36-225_com.android.chrome.jpg](https://user-images.githubusercontent.com/68321987/136684776-c4999877-91a2-47e3-b11a-e1dc340c3657.jpg)

**Comment by tushar152** [comment]
I also want to work on this project to make it more interactive, can you assign me?

**Comment by ManpreetKaur1469** [comment]
This project seems interesting to me, can I contribute?
